In [2]:
import pandas as pd

In [3]:
pair_wise_out = pd.read_csv("Leave-one-out Pilot.csv") 
pair_wise_in = pd.read_csv("Odd-one-out.csv")

In [6]:
true_labels = pair_wise_in.Label.values[:15]
true_labels

array([0, 2, 3, 4, 0, 3, 2, 0, 0, 1, 2, 4, 0, 4, 4], dtype=int64)

In [7]:
pair_wise_out["Input.Record1"][:15]

0             'Fraggment an sich I (Weltentraum)'
1             'Fraggment an sich I (Weltentraum)'
2             'Fraggment an sich I (Weltentraum)'
3             'Fraggment an sich I (Weltentraum)'
4             'Fraggment an sich I (Weltentraum)'
5     "Véronique Rivière - Baby, I'm a Want You" 
6     "Véronique Rivière - Baby, I'm a Want You" 
7     "Véronique Rivière - Baby, I'm a Want You" 
8     "Véronique Rivière - Baby, I'm a Want You" 
9     "Véronique Rivière - Baby, I'm a Want You" 
10                       "Don't Dream It's Over" 
11                       "Don't Dream It's Over" 
12                       "Don't Dream It's Over" 
13                       "Don't Dream It's Over" 
14                       "Don't Dream It's Over" 
Name: Input.Record1, dtype: object

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
       ...  
70    Item 4
71    Item 4
72    Item 4
73    Item 4
74    Item 4
Name: Answer.one-out.label, Length: 75, dtype: object

In [13]:
output_labels=pair_wise_out["Answer.one-out.label"].values

In [19]:
output_labels

array([nan, nan, nan, nan, nan, 'Item 2', 'Item 2', 'Item 2', 'Item 2',
       'Item 2', 'Item 3', 'Item 3', 'Item 3', 'Item 3', 'Item 3',
       'Item 4', 'Item 4', 'Item 4', 'Item 4', 'Item 4', nan, nan, nan,
       nan, nan, 'Item 3', 'Item 3', 'Item 3', 'Item 3', 'Item 3',
       'Item 2', 'Item 2', 'Item 2', 'Item 2', 'Item 2', nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, 'Item 1', 'Item 1', 'Item 1',
       'Item 1', 'Item 1', 'Item 2', 'Item 2', 'Item 2', 'Item 2',
       'Item 2', 'Item 4', 'Item 4', 'Item 4', 'Item 4', 'Item 4', nan,
       nan, nan, nan, nan, 'Item 4', 'Item 4', 'Item 4', 'Item 4',
       'Item 4', 'Item 4', 'Item 4', 'Item 4', 'Item 4', 'Item 4'],
      dtype=object)

In [20]:
numeric_ol = []
for i in output_labels:
    if i=="Item 1":
        numeric_ol.append(1)
    elif i=="Item 2":
        numeric_ol.append(2)
    elif i=="Item 3":
        numeric_ol.append(3)
    elif i=="Item 4":
        numeric_ol.append(4) 
    else:
        numeric_ol.append(0)    

In [21]:
no_of_workers= 5
worker_labels=[]
for i in range(0,len(numeric_ol),no_of_workers):
    worker_labels.append(numeric_ol[i:i+no_of_workers])


In [22]:
worker_labels

[[0, 0, 0, 0, 0],
 [2, 2, 2, 2, 2],
 [3, 3, 3, 3, 3],
 [4, 4, 4, 4, 4],
 [0, 0, 0, 0, 0],
 [3, 3, 3, 3, 3],
 [2, 2, 2, 2, 2],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1],
 [2, 2, 2, 2, 2],
 [4, 4, 4, 4, 4],
 [0, 0, 0, 0, 0],
 [4, 4, 4, 4, 4],
 [4, 4, 4, 4, 4]]

In [23]:
# Majority voting with 5.
single_label_5=[]
for i in (worker_labels):
    (single_label_5.append(pd.Series(i).value_counts().index[0]))
    

In [24]:
#Majority voting with 3.
single_label_3=[]
for i in (worker_labels):
    (single_label_3.append(pd.Series(i[:3]).value_counts().index[0]))

In [25]:
single_label_5

[0, 2, 3, 4, 0, 3, 2, 0, 0, 1, 2, 4, 0, 4, 4]

In [26]:
single_label_3

[0, 2, 3, 4, 0, 3, 2, 0, 0, 1, 2, 4, 0, 4, 4]

In [27]:
import numpy as np

In [32]:
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import confusion_matrix
from sklearn.metrics import multilabel_confusion_matrix

In [33]:
#precision, recall, f_score.
precision_recall_fscore_support(true_labels, single_label_5, average='macro')

(1.0, 1.0, 1.0, None)

In [34]:
#precision, recall, f_score. 
precision_recall_fscore_support(true_labels, single_label_3, average='macro')

(1.0, 1.0, 1.0, None)

precision_recall curve is not possible as no probabilities are involved in the sense that majority voting is used to determine labels and not a classifier for which the threshold can be varied!^<<..>>./\../\. 

In [38]:
multilabel_confusion_matrix(true_labels, single_label_3)# its the same for 5 workers here. 
#Nothing really to see here all True positives and True negatives are correctly identified for all different options basically...

array([[[10,  0],
        [ 0,  5]],

       [[14,  0],
        [ 0,  1]],

       [[12,  0],
        [ 0,  3]],

       [[13,  0],
        [ 0,  2]],

       [[11,  0],
        [ 0,  4]]], dtype=int64)

In [39]:
#Oh we need no folks for this task!