In [9]:
import pandas as pd

In [10]:
pair_wise_out = pd.read_csv("Output/leave-one-out.csv") 
pair_wise_in = pd.read_csv("Odd-one-out.csv")

In [11]:
true_labels = pair_wise_in.Label.values[:30]
true_labels

array([0, 2, 3, 4, 0, 3, 2, 0, 0, 1, 2, 4, 0, 4, 4, 0, 4, 1, 0, 2, 1, 0,
       2, 4, 3, 2, 4, 3, 3, 1], dtype=int64)

In [12]:
len(pair_wise_out["Input.Record1"])

210

In [13]:
pair_wise_in["Record1"]

0                  'Fraggment an sich I (Weltentraum)' 
1           "Véronique Rivière - Baby, I'm a Want You" 
2                              "Don't Dream It's Over" 
3                                  'Hard on Me - Gold' 
4                                         'Daytime TV' 
5                                  '001-Dil Ka Rishta' 
6                                 "Walkin' on the Sun" 
7                        '012-Owner of a Lonely Heart' 
8           'Love Forsaken (In A Dream Full Of Charm)' 
9                                  I'll Get By (Della) 
10                'Elvis Presley - Riding the Rainbow' 
11                                "Bouncin' In Rhythm" 
12    'Where Is the Conscience of the World (Adventu...
13                                        'Spaced Out' 
14                              '003-The Glass Forest' 
15                      'Travel (live) (amparo fugaz)' 
16      'Wat had je dan (feat. Moorder E) (El Patron)' 
17                                            'A

In [14]:
output_labels=pair_wise_out["Answer.one-out.label"].values

In [15]:
output_labels

array([nan, nan, nan, nan, nan, nan, nan, 'Item 1', 'Item 2', 'Item 2',
       'Item 2', 'Item 2', 'Item 2', 'Item 2', 'Item 3', 'Item 1',
       'Item 3', 'Item 3', 'Item 3', 'Item 3', 'Item 3', 'Item 4',
       'Item 4', nan, 'Item 4', 'Item 4', 'Item 4', 'Item 4', 'Item 4',
       'Item 4', nan, 'Item 1', nan, nan, nan, 'Item 3', 'Item 3',
       'Item 4', 'Item 3', 'Item 3', 'Item 3', 'Item 3', 'Item 2',
       'Item 2', 'Item 2', 'Item 2', 'Item 2', 'Item 2', 'Item 1', nan,
       nan, nan, nan, nan, 'Item 4', nan, nan, nan, 'Item 2', nan, nan,
       nan, 'Item 3', 'Item 1', 'Item 1', 'Item 1', 'Item 3', 'Item 1',
       'Item 1', 'Item 1', 'Item 2', 'Item 2', 'Item 2', 'Item 2',
       'Item 2', 'Item 2', 'Item 2', 'Item 3', 'Item 4', 'Item 4',
       'Item 4', 'Item 4', 'Item 4', 'Item 4', 'Item 4', nan, nan, nan,
       'Item 4', nan, 'Item 1', 'Item 4', 'Item 4', 'Item 4', 'Item 4',
       'Item 4', 'Item 4', nan, 'Item 4', nan, 'Item 4', 'Item 4',
       'Item 4', 'Item 4', 

In [16]:
numeric_ol = []
for i in output_labels:
    if i=="Item 1":
        numeric_ol.append(1)
    elif i=="Item 2":
        numeric_ol.append(2)
    elif i=="Item 3":
        numeric_ol.append(3)
    elif i=="Item 4":
        numeric_ol.append(4) 
    else:
        numeric_ol.append(0)    

In [17]:
no_of_workers= 7
worker_labels=[]
for i in range(0,len(numeric_ol),no_of_workers):
    worker_labels.append(numeric_ol[i:i+no_of_workers])


In [18]:
worker_labels

[[0, 0, 0, 0, 0, 0, 0],
 [1, 2, 2, 2, 2, 2, 2],
 [3, 1, 3, 3, 3, 3, 3],
 [4, 4, 0, 4, 4, 4, 4],
 [4, 4, 0, 1, 0, 0, 0],
 [3, 3, 4, 3, 3, 3, 3],
 [2, 2, 2, 2, 2, 2, 1],
 [0, 0, 0, 0, 0, 4, 0],
 [0, 0, 2, 0, 0, 0, 3],
 [1, 1, 1, 3, 1, 1, 1],
 [2, 2, 2, 2, 2, 2, 2],
 [3, 4, 4, 4, 4, 4, 4],
 [4, 0, 0, 0, 4, 0, 1],
 [4, 4, 4, 4, 4, 4, 0],
 [4, 0, 4, 4, 4, 4, 4],
 [3, 4, 0, 0, 0, 0, 0],
 [4, 4, 4, 4, 1, 4, 4],
 [1, 1, 1, 1, 1, 1, 1],
 [0, 2, 0, 0, 0, 0, 0],
 [2, 2, 2, 2, 2, 0, 2],
 [1, 2, 1, 1, 1, 1, 1],
 [0, 0, 0, 0, 0, 2, 0],
 [2, 2, 2, 2, 2, 2, 2],
 [4, 4, 4, 0, 4, 4, 4],
 [3, 3, 3, 3, 3, 1, 3],
 [2, 2, 2, 2, 1, 2, 2],
 [4, 4, 4, 4, 4, 4, 4],
 [3, 3, 3, 3, 3, 3, 3],
 [1, 3, 3, 3, 3, 3, 3],
 [1, 1, 1, 1, 2, 1, 1]]

In [19]:
# Majority voting with 7.
single_label_7=[]
for i in (worker_labels):
    (single_label_7.append(pd.Series(i).value_counts().index[0]))
    

In [20]:
single_label_7

[0,
 2,
 3,
 4,
 0,
 3,
 2,
 0,
 0,
 1,
 2,
 4,
 0,
 4,
 4,
 0,
 4,
 1,
 0,
 2,
 1,
 0,
 2,
 4,
 3,
 2,
 4,
 3,
 3,
 1]

In [21]:
import numpy as np

In [22]:
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import confusion_matrix
from sklearn.metrics import multilabel_confusion_matrix

In [24]:
#precision, recall, f_score.
precision_recall_fscore_support(true_labels, single_label_7, average='macro')

(1.0, 1.0, 1.0, None)

precision_recall curve is not possible as no probabilities are involved in the sense that majority voting is used to determine labels and not a classifier for which the threshold can be varied!^<<..>>./\../\. 

In [26]:
multilabel_confusion_matrix(true_labels, single_label_7)# its the same for 5 workers here. 
#Nothing really to see here all True positives and True negatives are correctly identified for all different options basically...

array([[[22,  0],
        [ 0,  8]],

       [[26,  0],
        [ 0,  4]],

       [[24,  0],
        [ 0,  6]],

       [[25,  0],
        [ 0,  5]],

       [[23,  0],
        [ 0,  7]]], dtype=int64)